version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: monthly
  - package-ecosystem: "gradle" 
    directory: "/router/"
    open-pull-requests-limit: 99
    schedule:
      interval: monthly
  - package-ecosystem: "gradle" 
    directory: "/router-protobuf/"
    open-pull-requests-limit: 99
    schedule:
      interval: monthly
  - package-ecosystem: "gradle" 
    directory: "/router-openapi-request-validator/"
    open-pull-requests-limit: 99
    schedule:
      interval: monthly
  - package-ecosystem: "gradle" 
    directory: "/samples/lambda-kotlin-request-router-sample/"
    open-pull-requests-limit: 99
    schedule:
      interval: monthly
  - package-ecosystem: "gradle" 
    directory: "/samples/lambda-kotlin-request-router-sample-proto"
    open-pull-requests-limit: 99
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: monthly
