version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: monthly
